### ISSUE TITLE
Exception with script path containing spaces

### ISSUE THREAD

**Issue by csphoenix1** [bugy/script-server#106]
Hi !

If there is one or more spaces in the script path, the script path is interpreted as a script path with arguments.

It's not the expected behavior :)

**Comment by bugy** [comment]
Hi @csphoenix1, to be honest, it's somehow expected behaviour :) #53 
Script_path parameter can be a command like 'python my_script.py' or 'java -jar my_app.jar'.
So if a filename contains spaces, it should be wrapped with a quote, e.g.
"script_path": " 'my script.sh' " (spaces around quotes are not needed)

However, I'll improve the behaviour: if the file with spaces exist, then script_path will be treated as a filename, and if there is no such file, then it will be treated as a complex command

**Comment by csphoenix1** [comment]
Hi @bugy ,

Oh yes! I didn't saw it #53.

Ok, so... perfect ^^ as usual ;)

And again: great job!

**Comment by bugy** [comment]
Done. Now if file_path contains whitespaces and is a real file (in working folder), then it will be treated as a single argument. Otherwise (if file doesn't exist), then script_path will be split into multiple arguments (as before).
However such configs should be avoided and explicit quotes should be used.

**Comment by bugy** [comment]
Works fine on windows
