### ISSUE TITLE
No output displayed - WebSocket issue with Nginx proxy

### ISSUE THREAD

**Issue by tristanlepachyderme** [bugy/script-server#110]
Hi,

First, bravo for your work, this application is exactly what a lot of people need.
I have an issue though...
I configured a test script that only echo 'Hey', it launches correctly but no output is written in the script page, just "Calling the script...". The output appears correctly in the admin page and the process logs.
We can note a warning in the server log :
```
[tornado.access.INFO] 200 POST /scripts/execute (127.0.0.1) 7.44ms
[tornado.access.WARNING] 400 GET /scripts/execute/io/21 (127.0.0.1) 0.76ms
[tornado.general.DEBUG] Can "Upgrade" only to "WebSocket".
```

I'm running Red Hat 6.9, Python 3.6.5 and Script-Server 1.11.0
Any help would be appreciated !
Thanks,

Tristan

**Comment by tristanlepachyderme** [comment]
Ok, the issue come from the Nginx proxy, some configuration in order to support WebSocket was needed
```
server{ ...
location / { ...
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
}
}
```
But, now tornado is saying that cross origin websockets are not allowed
```
[tornado.access.INFO] 200 POST /scripts/execute (10.155.16.126) 113.26ms
[tornado.access.WARNING] 403 GET /scripts/execute/io/65 (10.155.16.126) 1.68ms
[tornado.general.DEBUG] Cross origin websockets not allowed
```

**Comment by tristanlepachyderme** [comment]
This solved my issue.
Thanks.
https://github.com/bugy/script-server/wiki/Using-as-a-reverse-proxy

**Comment by bugy** [comment]
Hi, thank you for the feedback and I'm glad that it worked for you :)

**Comment by ndvbd** [comment]
I get lines like these:

WARNING:tornado.access:400 GET /ws (88.85.242.22) 0.41ms

anyone know what it means?

**Comment by bugy** [comment]
@ndvbd I guess the socket is not being upgraded probably, double check reverse proxy configs and make sure websocket modules are installed

**Comment by ndvbd** [comment]
Thanks @bugy, I have this
```
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}

```
and this

```
proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
```
 in the nginx config. How can I dive deeper to debug this issue? What does it even mean 400 GET? I know that 400 is an error code for HTTP response, but aren't we talking here about a request in the tornado.access logging?

**Comment by ndvbd** [comment]
@bugy 
1. Server is functioning for me, but maybe there are some clients that it is not function for them, that's why I want to investigate this print.
2. I don't have a logging.json. Where in the python tornado code I specify the file path? Or can it be done programmatically? 
3. Just to be clear, I don't want to silence everything, just this specific "websocket upgrade" case, so it would be better to have some logging function that I can override and be able to place breakpoints/prints in, and then choose to silence things programmatically.

**Comment by bugy** [comment]
2. I'm pretty sure you should hae it, otherwise the startup will fail. Anyway, you can create it, and take it from here as example: https://github.com/bugy/script-server/blob/master/conf/logging.json
3. the best you can disable via config, is warnings to `tornado.access`
4. Actually my bad here, I didn't read your first message carefully. it's an access to `/ws` endpoint, which is not used in script server. So I don't know who and why is trying to access it

**Comment by ndvbd** [comment]
My apologies! I just realized that I've put the question in the wrong github repository! I was confused by the title of the issue. I actually need to place it in the Tornado Github repo, as it has nothing to do with script-server! Sorry...
