### ISSUE TITLE
add variable of current operator

### ISSUE THREAD

**Issue by muzzol** [bugy/script-server#130]
we use an OPERATOR and SERVER variable on our scripts to keep track of who is executing what.

for example

    /opt/scripts/test1.sh $OPERATOR -p test -t test

so it would be great to have a variable with current logged user in a variable.

I think we can user double dollar to get current machine, so that part is covered.

ask for further info if you need more details

**Comment by bugy** [comment]
Hi @muzzol, sounds reasonable. Do I understand correctly, that it should be a constant parameter and it should be filled with current user name? 
Example:
```
"parameters": [
    {
        "name": "operator",
        "const": true,
        "default": "${auth.username}"
    }
]
```

**Comment by bugy** [comment]
Added possibility to use current user in a parameter's `default` field. This can be used for prefilling a value on UI _or_  as a constant parameter.
There are 2 options:
- username - name of the authenticated user (if auth is not enabled, it will be empty)
- audit_name - when auth is enabled, it's the same as username. Otherwise it's hostname, IP or basic auth credentials. 

In order to specify those, please use either `${auth.username}` or `${auth.audit_name}` placeholders

Example:
```
    {
      "name": "Auth username",
      "param": "-u",
      "default": "${auth.username}"
    },
    {
      "name": "Audit name",
      "constant": true,
      "param": "--audit_name",
      "default": "${auth.audit_name}"
    }
```

**Comment by muzzol** [comment]
can this be configured on script values?

for example, I need something like this

```
    {
      "name": "Roles",
      "type": "list",
      "values": { "script": "/opt/scripts/list_rols.sh ${auth.audit_name}" }
    },


```


is that possible?

**Comment by bugy** [comment]
Hi @muzzol unfortunately at the moment it's not. But could be done

**Comment by muzzol** [comment]
ok, do you want me to open a new issue or is enoug reopening this one?

**Comment by bugy** [comment]
The new would be better, thanks!
