### ISSUE TITLE
Server folder or file as input parameter for my script

### ISSUE THREAD

**Issue by fabianomenegidio** [bugy/script-server#137]
How can I select a folder or file as input parameter for my script?

**Comment by bugy** [comment]
Hi @fabianomenegidio, for file parameter you can you [file_upload type](https://github.com/bugy/script-server/wiki/Script-config#--type). There are details on how it works: [details](https://github.com/bugy/script-server/wiki/Script-config#file_upload)

Uploading the folder is not supported. And it would be complicated to implement, because it's not really supported by html standards and would work only in some browsers.

Or did I understand your question wrong and you were asking about selecting a file/folder on the server?

**Comment by fabianomenegidio** [comment]
Choose a file or folder on the server (in a container where Script-Server would be installed).

Tnx

**Comment by bugy** [comment]
Hi @fabianomenegidio, unfortunately it's not supported at the moment. 

If you have limited amount of files, you can emulate this behaviour with a list parameter, specifying `ls`/`find` as a command.
E.g. 
```
{
      "name": "File on server",
      "type": "list",
      "values": {
        "script": "find /home/me/folder -name '*.txt'"
      }
}
```

**Comment by bugy** [comment]
Hi @fabianomenegidio, I'd keep the issue open until I add the feature

**Comment by bugy** [comment]
There is another similar ticket: #147, which I can be addressed together. 
In my opinion there could be 2 different options: recursive and not. For recursive option there would be some kind of file selection dialog.
For non-recursive it would be shown as a list.

**Comment by bugy** [comment]
@csphoenix1 I added 'server_file' parameter type. It can be used for non-recursive file selection. For the user only filenames will be shown. In the script full path (i.e. `file_dir`/filename) will be passed

Also added new parameter configuration fields:
`file_dir` - (required) where to look for files
`file_type` - file type filter ('dir' or 'file')
`file_extensions` - list of file extensions (implicitly applies `"file_type": "file"`)

Example config:
```
{
    "name": "my file",
    "type": "server_file",
    "file_dir": "/home/me/configs",
    "file_extensions": ["txt", "yml", "json"]
}
```

Recursive file selection still to be done

**Comment by bugy** [comment]
Added new parameter option: `file_recursive` (boolean). If it's true, then instead of combobox, user will get a file chooser with the possibility to navigate between folders and select them.
The "root" dir for the user will be the `file_dir` and user won't be able to see/select anything outside of it.

Also fixed interaction of `file_dir` and `working_dir`. Now `file_dir` is relative to `working_dir`.

Examples could be found in https://github.com/bugy/script-server/blob/master/samples/configs/parameterized.json
