### ISSUE TITLE
Add possibility to enable access to admin page for anyone

### ISSUE THREAD

**Issue by yarongolan** [bugy/script-server#178]
Would it be possible to have a configuration parameter that just allows anyone to use the system and to access the admin (or at least the LOGS) page?

**Comment by yarongolan** [comment]
The use case is just to see the logs. Specifically, I am setting up a simple solution where I'd like anyone with access to the intranet to see the previous runs to confirm all went well, or to trace and fix issues. Limited user base, no need for auth.

**Comment by yosefy** [comment]
also after just installing the server, i don't want to deal with auth
but i want to play with admin page first for a second

**Comment by bugy** [comment]
Thanks for the comments!

@yosefy by default access to the admin page is allowed from localhost. 
Giving access to admin page by default to everyone looks very dangerous for me, because there is a huge chance that after "playing", the `admin_users` setting will be forgotten and will be moved to PROD with full access to everyone.
And admin page will become truly admin in the next release, I hope, where you would be able to create/change scripts, thus giving access to the whole server machine

**Comment by yosefy** [comment]
may be you can add the option of * then?

**Comment by bugy** [comment]
Ye, this is what I'll do

**Comment by yosefy** [comment]
actually i saw lots of cases where people test stuff on small AWS instance or such (including me :) ),
thats why the may be good idea

thanks a lot

**Comment by bugy** [comment]
Done. Now you can put `"admin_users": "*"` to make it accessible for anyone.
Please be careful with it: when admin page will be extended with script configurations, any user would be able to do anything with your server (where Script server is running). 

Also I could remove this option one day, as not very safe (but before that I'll introduce an option to view logs out of admin page)
Not going to document this option anywhere (except this task)
