### ISSUE TITLE
Store script output and allow to view it

### ISSUE THREAD

**Issue by MadDud** [bugy/script-server#230]
Hi Bugy,

Would you consider adding a feature to store outputs of scripts? 

It would be great, if it was possible to view previously displayed script outputs. There could be a table/list of events with date and script name, and when you click on it, you see the full script output. Or a list (dropdown) in each script view.

**Comment by bugy** [comment]
Hi @MadDud, this feature is there almost since the beginning of the project :) But it's only for admins:
1. Either you can check files in logs/processes
2. Or in the admin.html page, see https://github.com/bugy/script-server/wiki/Authorization#admin-users for details

**Comment by MadDud** [comment]
admin.html - this is exactly what I was talking about.
I couldn't see this feature, because was unable to access admin panel. I changed config and now I can see it. 

```
{
"access": { 
        "admin_users": ["172.17.0.1-a33c5c970b5e42dd"]
        }
}
```

It would be amazing to have access to this history for every script and without admin rights though.

**Comment by bugy** [comment]
Hi @MadDud, in the future I plan to add the possibility for users to view own logs. But I'm not sure about giving a user rights, to view logs of other users (due to security reasons). 

By the way, for now you can make everyone an admin, by putting "*" in the admin_users. Though be careful, in 1.15 I'm going to add script configuration feature to the admin panel, so may be you don't want anyone to access it.

**Comment by MadDud** [comment]
> in the future I plan to add the possibility for users to view own logs. But I'm not sure about giving a user rights, to view logs of other users

This would be great!

Thanks for the heads up about the "*" and new admin panel features.
