### ISSUE TITLE
Issue with secure parameter on v 1.15

### ISSUE THREAD

**Issue by juliostanley** [bugy/script-server#265]
It seems like v1.15 introduced an issue that allows code injection?

Secure text parameters are being ran as is (so if a password has spaces, it's treated as 2 params)

Thoughts?

**Comment by bugy** [comment]
Hi @juliostanley, thanks for heads up!

But to be honest I don't think so. I checked it locally and it seems good (it was passed as a single parameter). 
Also, on linux/mac it cannot cause code injection for script server in any case (even though because of bugs, it can mess up parameters, but never execute any other code)

However, it can be that the script itself can handle parameters incorrectly. For example, if I have parameter `my_var='abc def'` and then do `ls $1` then the output will be 
```
ls: cannot access 'abc': No such file or directory
ls: cannot access 'def': No such file or directory
```
So double quotes should be used: `ls "$my_var"`

If it's not the case, it would be nice, if you could share a sample script and a configuration

**Comment by juliostanley** [comment]
Thank you for looking into this. Let me test again, and I'll update.

**Comment by juliostanley** [comment]
Yes, my bad.

I got confused because I was running it in dind and chroot called /bin/sh -c passing "$@", I modified it to call a specific a bin on chroot instead and pass args without interpolating within a -c command

I don't use binaries in script server, script server calls docker containers via an alias shell that communicates with chroot (everything is running on kubernetes within a dind).

Thank you
