### ISSUE TITLE
Heroku error

### ISSUE THREAD

**Issue by mishailovic** [bugy/script-server#296]
I am trying to deploy the server on the heroku, and getting this error in the web interface: 
![IMG_20200424_151553](https://user-images.githubusercontent.com/41520056/80211569-a0144a00-863e-11ea-957a-11bb9b9bbc1e.jpg)

**Comment by bugy** [comment]
The script is marked as not executable. You need to make chmod +x on it. On
the remote server

Mikhail Kuznetsov <notifications@github.com> schrieb am Fr., 24. Apr. 2020,
14:17:

**Comment by mishailovic** [comment]
Heroku does not give access to the terminal.  I can only deploy apps from github repositories

**Comment by bugy** [comment]
Unfortunately i never worked with heroku and cannot give much tips here.
You would need to find a way, how to make the script executable on the
remote server

As alternative, you can try adding the interpreter before the script, in
the json file, e.g.
"script_path": "bash my_script.sh"
Or python instead of bash, for a python script
Or any other

But i would highly recommend finding a way to give permissions instead :)

Mikhail Kuznetsov <notifications@github.com> schrieb am Fr., 24. Apr. 2020,
14:45:

**Comment by mishailovic** [comment]
Well, if I find a solution, I will definitely write it here.  Thank you very much for quick reply :3

**Comment by mishailovic** [comment]
Yeah, finally fixed it, i just redeployed the app with new configuration file:
```
{
  "name": "Test",
  "script_path": "python myscript.py",
  "working_directory": "./scripts",
  "parameters": []
}
```

And it works brilliant.
Mabe you should add this solution to the readme, because not only me use heroku.

**Comment by bugy** [comment]
Hi @mishailovic, thanks for confirming!

To be honest, I'm a bit skeptical to suggest it as a recommendation because it's more prone to script injection and there can be edge cases in Script server when it cannot parse such `script_path` properly

I'll keep it as an issue here, so other people would be able to find it if needed. And if there would be more complaints, I'll reconsider my recommendations :)
