### ISSUE TITLE
font color of script header

### ISSUE THREAD

**Issue by fnpanic** [bugy/script-server#535]
Hi,

is it possible to independently change the font color on the script header?

Changing the --font-on-primary-color-main from black to wihte messes things up in some parts. I am using a pretty dark color for the script header so white would be great.

Do i need to define a new css var and modify the web/css/index.37d9c877.css or is there a smater way?

**Comment by bugy** [comment]
You can actually add a custom style to your custom css document
So check which classes/id does the element have, and specify it in the css file

**Comment by fnpanic** [comment]
Thanks @bugy 

Adding

```
h2.header {
    color: white;
}
```
to conf/theme/theme.css did the trick!

**Comment by fnpanic** [comment]
Just a small question.

It seems like history uses a different header.

i added 

```
h3.header {
    color: white;
}
```

to theme.css but the color stays black. Maybe you have a hint for me

**Comment by bugy** [comment]
Try using `div.main-content-header a.breadcrumb h3.header`
I guess default style takes precedence, over your custom style, because it's more specific than `h3.header`.

styles.css (as per documentation) are for variables only. Injecting custom CSS there is an undocumented feature and works as it is :)

**Comment by fnpanic** [comment]
@bugy yes this did the trick. Thank you very much!
